# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
  #schedule:
  #  - cron: '*/30 * * * *'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scraper
        run: pyton3 LotrTCG.py
